#!/usr/bin/csh

setenv  SCCS_DIR  "~/Project_SCCS/"

setenv CURRENT_DIR `pwd`

cd $SCCS_DIR

 sccs get -e   database2.cpp
 sccs get -e   llist.cpp
 sccs get -e   llist.h
 sccs get -e   record.h
 sccs get -e   Database.txt
 sccs get -e   Makefile
 
mv database2.cpp $CURRENT_DIR/.
mv llist.cpp $CURRENT_DIR/.
mv llist.h $CURRENT_DIR/.
mv record.h $CURRENT_DIR/.
mv Database.txt $CURRENT_DIR/.
mv Makefile $CURRENT_DIR/.


cd $CURRENT_DIR





 
